resources:
- name: project-code
  type: git
  source:
    uri: https://github.com/Sathyan727/concourse-demo-job.git
    branch: main
 
jobs:
- name: build-ami
  plan:
  - get: project-code
    trigger: true
  - task: validate-packer
    vars:
      ssh-private-key: ((ssh-private-key))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hashicorp/packer
          tag: latest
      inputs:
      - name: project-code
      run:
        path: sh
        args:
        - -c
        - |
          packer plugins install github.com/hashicorp/amazon
          packer plugins install github.com/hashicorp/ansible
          packer validate project-code/packer/template.json
  - task: build-ami
    vars:
      ssh-private-key: ((ssh-private-key))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hashicorp/packer
          tag: latest
      inputs:
      - name: project-code
      run:
        path: sh
        args:
        - -c
        - |
          packer build -var 'aws_access_key=${AWS_ACCESS_KEY}' -var 'aws_secret_key=${AWS_SECRET_KEY}' project-code/packer/template.json
 
- name: provision-infra
  plan:
  - get: project-code
    passed: [build-ami]
  - task: terraform-init
    vars:
      ssh-private-key: ((ssh-private-key))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hashicorp/terraform
          tag: latest
      inputs:
      - name: project-code
      run:
        path: sh
        args:
        - -exc
        - |
          cd project-code/terraform
          terraform init
  - task: terraform-apply
    vars:
      ssh-private-key: ((ssh-private-key))  
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hashicorp/terraform
          tag: latest
      inputs:
      - name: project-code
      params:
        TF_VAR_ami_id: ((ami_id))
      run:
        path: sh
        args:
        - -exc
        - |
          cd project-code/terraform
          terraform apply -auto-approve
 
