---
- hosts: all
  become: true
  tasks:
    - name: Update yum cache
      command: yum makecache
      register: yum_cache
      failed_when: yum_cache.rc != 0

    - name: Install Python 3 and pip
      command: yum install -y python3 python3-pip curl
      register: python_install
      failed_when: python_install.rc != 0

    - name: Install Java and utilities
      command: yum install -y java-11-openjdk-devel nano curl wget vim zip unzip
      register: java_install
      failed_when: java_install.rc != 0
